version: "3"
services:
  db:
    environment:
      - TZ=Asia/Bangkok
      - LANG=C.UTF-8
      - MYSQL_ROOT_PASSWORD=oasiptt2
    image: mysql:8
    volumes:
      - ./database/script:/docker-entrypoint-initdb.d/

  spring:
    build: ./oasip-service
    depends_on:
      - db
    restart: on-failure
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.driver-class-name":"com.mysql.cj.jdbc.Driver",
        "spring.datasource.password":"oasiptt2",
        "spring.datasource.username":"test221",
        "spring.datasource.url":"jdbc:mysql://db:3306/oasip?connectionTimeZone=SERVER",
        "spring.jpa.hibernate.ddl-auto":"none",
        "spring.jpa.hibernate.naming.physical-strategy":"org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl",
        "server.error.include-message":"always",
        "jwt.secret":"oasiptt2",
        "jwt.jwtExpirationInMs":"1800000",
        "jwt.refreshExpirationDateInMs":"86400000",
        "spring.mail.host":"smtp.gmail.com",
        "spring.mail.port":"587",
        "spring.mail.username":"thunnavat.c@mail.kmutt.ac.th",
        "spring.mail.password":"prompetkuajparxu",
        "spring.mail.properties.mail.smtp.auth":"true",
        "spring.mail.properties.mail.smtp.starttls.enable":"true",
        "spring.servlet.multipart.max-file-size":"10MB",
        "spring.servlet.multipart.max-request-size":"10MB",
        "upload.path":"/home/spadmin/serverFile/"
      }'
 
  vue:
    build: 
      context: "./oasip-vue"
      args:
        - VITE_API_URL=/tt2/api
    depends_on:
      - spring
  
  reverse:
    build: "./reverse-proxy"
    ports:
      - "80:80"
      - "443:443"
